add

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,7 +1,21 @@
 #!/usr/bin/env bash
 # Installs Nginx
 
-apt-get update
-apt-get install -y nginx
-echo "Hello World!" | sudo tee  /var/www/html/index.html
+# Update the package list
+sudo apt-get update
+
+# Install Nginx
+sudo apt-get install -y nginx
+
+# Create a simple HTML file
+echo "Hello World!" | sudo tee /var/www/html/index.html
+
+# Start the Nginx service
 sudo service nginx start
+
+# Check if Nginx started successfully
+if [ $? -eq 0 ]; then
+    echo "Nginx has been installed and started successfully."
+else
+    echo "Error: Nginx installation or startup failed."
+fi
